/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, File, GradientStop, Image, LinearGradient, Point2D } from "@diez/prefabs";

const diezTestColors = {
    white: Color.rgba(255, 255, 255, 1),
    pink: Color.rgba(230, 55, 168, 1)
};

const diezTestGradients = {
    gradient: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(28, 200, 225, 1)), GradientStop.make(1, Color.rgba(208, 34, 237, 1))], start: Point2D.make(0.011643373314405, 0.011093128195558), end: Point2D.make(0.984476033765627, 0.99128417026002) })
};

export const diezTestImagesFiles = {
    badgeUnincorn: new File({ src: "assets/DiezTest.figma.contents/images/BadgeUnincorn.png" }),
    badgeUnincorn2x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeUnincorn@2x.png" }),
    badgeUnincorn3x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeUnincorn@3x.png" }),
    badgeUnincorn4x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeUnincorn@4x.png" }),
    badgeMuzologyHeart: new File({ src: "assets/DiezTest.figma.contents/images/BadgeMuzologyHeart.png" }),
    badgeMuzologyHeart2x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeMuzologyHeart@2x.png" }),
    badgeMuzologyHeart3x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeMuzologyHeart@3x.png" }),
    badgeMuzologyHeart4x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeMuzologyHeart@4x.png" }),
    badgeFunction: new File({ src: "assets/DiezTest.figma.contents/images/BadgeFunction.png" }),
    badgeFunction2x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeFunction@2x.png" }),
    badgeFunction3x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeFunction@3x.png" }),
    badgeFunction4x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeFunction@4x.png" }),
    badgeDivide: new File({ src: "assets/DiezTest.figma.contents/images/BadgeDivide.png" }),
    badgeDivide2x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeDivide@2x.png" }),
    badgeDivide3x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeDivide@3x.png" }),
    badgeDivide4x: new File({ src: "assets/DiezTest.figma.contents/images/BadgeDivide@4x.png" })
};

/**
 * This is provided for backward compatibility, please use `diezTestImagesFiles` instead.
 * @deprecated
 */
export const diezTestComponentsFiles = diezTestImagesFiles;

export const diezTestImages = {
    badgeUnincorn: Image.responsive("assets/DiezTest.figma.contents/images/BadgeUnincorn.png", 179.45126342773438, 193.51153564453125),
    badgeMuzologyHeart: Image.responsive("assets/DiezTest.figma.contents/images/BadgeMuzologyHeart.png", 183.8419189453125, 208.3541717529297),
    badgeFunction: Image.responsive("assets/DiezTest.figma.contents/images/BadgeFunction.png", 132.3773956298828, 166.174072265625),
    badgeDivide: Image.responsive("assets/DiezTest.figma.contents/images/BadgeDivide.png", 132.37741088867188, 166.17404174804688)
};

/**
 * This is provided for backward compatibility, please use `diezTestImages` instead.
 * @deprecated
 */
export const diezTestComponents = diezTestImages;

export const diezTestTokens = {
    colors: diezTestColors,
    gradients: diezTestGradients
};
